### ISSUE TITLE
How to convert from existing nagios/centreon settings  ?

### ISSUE THREAD

**Issue by pauld8758757** [mclarkson/nagrestconf#31]
Hi. I currently use a nagios/centreon installation to onitor my servers and discovered your software for synology wich is great. I installed it without any problem but then i blocked into importing my current settings from nagios. Is there an easy way to convert current nagios files and import them ? If yes how to proceed?
Thanks

**Comment by mclarkson** [comment]
No there is no simple way to import nagios files. Probably the most reliable way to do this would be to use something like livestatus so that a script could be written to create REST commands by querying it. It would be difficult to make this create service sets though.

If there are groups of hosts with the same configuration, such as apache or mysql, then service sets can be made for these hosts. With the service sets in place the CSV import could be used for bulk loading of hosts. After loading it is still possible to tweak the service and host configurations.

If I have to migrate a nagios configuration I generally do it by manually, grouping things into service sets, then applying them to hosts.

**Comment by pauld8758757** [comment]
Hi? Do you have by any chance the fields labels for the files in /var/packages/Synagios/target/nagios-chroot/etc/nagios3/objects/local/setup so that i can directly create the csv files ?
Thanks in advance as this seems to be the easiest solution

**Comment by pauld8758757** [comment]
oups seems i did find the answer on http://nagrestconf.smorg.co.uk/documentation/restreference.php#_hosts

**Comment by mclarkson** [comment]
Glad you found it :)
Note that some fields need to be Url encoded, marked with 'E' in the tables.
