### ISSUE TITLE
Commit mail errors

### ISSUE THREAD

**Issue by maestrx** [mclarkson/nagrestconf#43]
Hello,

I've 2 questions linked to my test enviornment running nagios, nagrestconf and other custom modules. Since come time I'm getting following error in the cron mails from commits:

Running configuration check...done.
Stopping nagios: .done.
Starting nagios: done.
cp: omitting directory `setup.known_good/setup'
svn: E170009: Commit failed (details follow):
svn: E170009: Repository UUID 'c8d6d6a3-e285-4aed-a084-00a13a85517f' doesn't match expected UUID '1614826a-c8c8-4224-825c-bb3fde820823'

Any idea how to fix it and why it happened? Restart works just fine and new configuration is applied.

I've answered myself to the second question :)

Thanks
Vit

**Comment by maestrx** [comment]
Relevant thing to note would be that I've moved the configuration directory between hosts as I've not found any migration instructions....

**Comment by mclarkson** [comment]
Did you try the backup/restore plugin?

**Comment by maestrx** [comment]
No really. Should I do backup, cleanup of the /etc/nagios/objects/local directory and restore?

**Comment by mclarkson** [comment]
You can delete the versions/ directory and it will be recreated. I think you have an old versions/ directory but a new svn repo, so there's a mismatch.

I don't think setup/ should be in setup.known_good/ either.

**Comment by mclarkson** [comment]
Did deleting the versions/ directory fix the issue for you?

When I said to use the backup/restore, I meant for the initial migration. This was why the user can restore a subset of the tables (using the check boxes), so that a backup can be made from one server and restored on another, but when restoring the data, the user has the option to not restore the hosts and services tables. This allows a generic configuration to be used on a number of nagios servers, each with different hosts and services.

Sorry my answers were so brief. I wrote them on the train, on my phone!

**Comment by maestrx** [comment]
Hi,

 

Removing the version dir did not help. So I did the backup, wiped out the whole config directory and ran restore. The GIU has been kind-of frozen at the beginning, but all worked out perfecly finally :)

 

Thanks

Vit

**Comment by mclarkson** [comment]
Glad it's sorted. I need a spinny thing!
