### ISSUE TITLE
Synology DS214Play + nagrestconf

### ISSUE THREAD

**Issue by stomp442** [mclarkson/nagrestconf#45]
I just installed synagios_0.14_jessie_repack_x86 on my DS214Play. Installed without issues. Configured the passwords, port, etc. per the directions on your site.

When I hit up nagrestconf to start configuring hosts, I get an error:
> NAGCTL ERROR: Invalid data. A required field is empty.

Hitting up the Google to find a solution, or some help, I found that this was address in a closed ticket
> Nagrestconf & Nagios3 Error #37

The solution on that ticket was to uninstall, and reinstall; which I did, but the issue persists.

Where can I find the logs for nagrestconf, to start looking for anything that might help out?

**Comment by mclarkson** [comment]
This is probably due to inadequate documentation with nagrestconf. See #40 - you're not alone.

To get going quickly, restore the example configuration using the section:

> [optional] Restore the sample backup configuration

from the [installation documentation](http://nagrestconf.smorg.co.uk/installguides/synology.php).

Once this is done, and you can confirm it works, you can delete the host (diskstation) if you want and start adding new hosts.

**Comment by mclarkson** [comment]
Oh, and the logs can be accessed in the DSM Admin interface. Open the Package Center, click on Synagios, then click on View Log.

**Comment by stomp442** [comment]
No worries about the documentation thing.

I guess that I didn't understand clearly that you'd posted sample data to get around this issue. I'm trying the sample data. I'll update this as soon as I have something.

RE: Log data. I found that right after I posted.

**Comment by stomp442** [comment]
Yeah. Close this up. Guess I should have read that documentation a little closer. Thanks for the help.

**Comment by mclarkson** [comment]
You're welcome and thanks for confirming :)
